config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  resources :data_files
  resources :dict_jobs
  resources :glossary_indices
  resources :progress_bars
  resources :users
  get 'export_glossary/export'
  get 'export_glossary/export_now'

  resources :glossaries
  resources :davkhkt_dicts
  resources :dict_configs
  root 'dict_pages#home'
  get 'admin_pages/admin_home'
  get 'admin_pages/config_dict'
  get 'admin_pages/config_dict_new'
  get 'admin_pages/config_dicts'
  get 'admin_pages/glossaries'
  get 'admin_pages/glossary_edit'
  get 'admin_pages/glossary_import'
  put 'admin_pages/glossary_import'
  get 'admin_pages/glossary_export'
  put 'admin_pages/glossary_export'
  get 'admin_pages/config_user'
  get '/home',    to: 'dict_pages#home'
  get '/help',    to: 'dict_pages#help'
  get '/about',   to: 'dict_pages#about'
  get '/error',   to: 'dict_pages#error'
  get '/admin',   to: 'dict_pages#admin'
  get '/signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  get '/dict_lookup',   to: 'dict_pages#dict_lookup'
  get '/dict_add',   to: 'dict_pages#dict_add'
  put '/glossaries',   to: 'glossaries#index'
  get '/progress' => 'dict_jobs#progress'

#  put  '/davkhkt_dicts',   to: 'davkhkt_dicts#index'
#  get 'dav_dict_pages/import'
#  get 'dav_dict_pages/show'
#  put  '/dict_import',   to: 'import_page#import_glossary'
#  get  '/dict_import',   to: 'import_page#import_glossary'
#  put  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get 'export_glossaries' => 'exports#export_glossaries', as: :export_glossaries

mount Sidekiq::Web, at: "/sidekiq"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/glossary_indices_controller.rb
class GlossaryIndicesController < ApplicationController
  before_action :set_glossary_index, only: [:show, :edit, :update, :destroy]

  # GET /glossary_indices
  # GET /glossary_indices.json
  def index
    @glossary_indices = GlossaryIndex.all
  end

  # GET /glossary_indices/1
  # GET /glossary_indices/1.json
  def show
  end

  # GET /glossary_indices/new
  def new
    @glossary_index = GlossaryIndex.new
  end

  # GET /glossary_indices/1/edit
  def edit
  end

  # POST /glossary_indices
  # POST /glossary_indices.json
  def create
    @glossary_index = GlossaryIndex.new(glossary_index_params)

    respond_to do |format|
      if @glossary_index.save
        format.html { redirect_to @glossary_index, notice: 'Glossary index was successfully created.' }
        format.json { render :show, status: :created, location: @glossary_index }
      else
        format.html { render :new }
        format.json { render json: @glossary_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /glossary_indices/1
  # PATCH/PUT /glossary_indices/1.json
  def update
    respond_to do |format|
      if @glossary_index.update(glossary_index_params)
        format.html { redirect_to @glossary_index, notice: 'Glossary index was successfully updated.' }
        format.json { render :show, status: :ok, location: @glossary_index }
      else
        format.html { render :edit }
        format.json { render json: @glossary_index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /glossary_indices/1
  # DELETE /glossary_indices/1.json
  def destroy
    @glossary_index.destroy
    respond_to do |format|
      format.html { redirect_to glossary_indices_url, notice: 'Glossary index was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_glossary_index
      @glossary_index = GlossaryIndex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def glossary_index_params
      params.require(:glossary_index).permit(:dict_id, :lang, :key_words, :digest)
    end
end

app/helpers/glossary_indices_helper.rb
module GlossaryIndicesHelper
end

app/views/glossary_indices/_form.html.erb
<%= form_with(model: glossary_index, local: true) do |form| %>
  <% if glossary_index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(glossary_index.errors.count, "error") %> prohibited this glossary_index from being saved:</h2>

      <ul>
      <% glossary_index.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dict_id %>
    <%= form.text_area :dict_id, id: :glossary_index_dict_id %>
  </div>

  <div class="field">
    <%= form.label :lang %>
    <%= form.text_area :lang, id: :glossary_index_lang %>
  </div>

  <div class="field">
    <%= form.label :key_words %>
    <%= form.text_area :key_words, id: :glossary_index_key_words %>
  </div>

  <div class="field">
    <%= form.label :digest %>
    <%= form.text_area :digest, id: :glossary_index_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/glossary_indices/edit.html.erb
<h1>Editing Glossary Index</h1>

<%= render 'form', glossary_index: @glossary_index %>

<%= link_to 'Show', @glossary_index %> |
<%= link_to 'Back', glossary_indices_path %>

app/views/glossary_indices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Glossary Indices</h1>

<table>
  <thead>
    <tr>
      <th>Dict</th>
      <th>Lang</th>
      <th>Key words</th>
      <th>Digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @glossary_indices.each do |glossary_index| %>
      <tr>
        <td><%= glossary_index.dict_id %></td>
        <td><%= glossary_index.lang %></td>
        <td><%= glossary_index.key_words %></td>
        <td><%= glossary_index.digest %></td>
        <td><%= link_to 'Show', glossary_index %></td>
        <td><%= link_to 'Edit', edit_glossary_index_path(glossary_index) %></td>
        <td><%= link_to 'Destroy', glossary_index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Glossary Index', new_glossary_index_path %>

app/views/glossary_indices/new.html.erb
<h1>New Glossary Index</h1>

<%= render 'form', glossary_index: @glossary_index %>

<%= link_to 'Back', glossary_indices_path %>

app/views/glossary_indices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dict:</strong>
  <%= @glossary_index.dict_id %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @glossary_index.lang %>
</p>

<p>
  <strong>Key words:</strong>
  <%= @glossary_index.key_words %>
</p>

<p>
  <strong>Digest:</strong>
  <%= @glossary_index.digest %>
</p>

<%= link_to 'Edit', edit_glossary_index_path(@glossary_index) %> |
<%= link_to 'Back', glossary_indices_path %>