config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  resources :data_files
  resources :dict_jobs
  resources :glossary_indices
  resources :progress_bars
  resources :users
  get 'export_glossary/export'
  get 'export_glossary/export_now'

  resources :glossaries
  resources :davkhkt_dicts
  resources :dict_configs
  root 'dict_pages#home'
  get 'admin_pages/admin_home'
  get 'admin_pages/config_dict'
  get 'admin_pages/config_dict_new'
  get 'admin_pages/config_dicts'
  get 'admin_pages/glossaries'
  get 'admin_pages/glossary_edit'
  get 'admin_pages/glossary_import'
  put 'admin_pages/glossary_import'
  get 'admin_pages/glossary_export'
  put 'admin_pages/glossary_export'
  get 'admin_pages/config_user'
  get '/home',    to: 'dict_pages#home'
  get '/help',    to: 'dict_pages#help'
  get '/about',   to: 'dict_pages#about'
  get '/error',   to: 'dict_pages#error'
  get '/admin',   to: 'dict_pages#admin'
  get '/signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  get '/dict_lookup',   to: 'dict_pages#dict_lookup'
  get '/dict_add',   to: 'dict_pages#dict_add'
  put '/glossaries',   to: 'glossaries#index'
  get '/progress' => 'dict_jobs#progress'

#  put  '/davkhkt_dicts',   to: 'davkhkt_dicts#index'
#  get 'dav_dict_pages/import'
#  get 'dav_dict_pages/show'
#  put  '/dict_import',   to: 'import_page#import_glossary'
#  get  '/dict_import',   to: 'import_page#import_glossary'
#  put  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get 'export_glossaries' => 'exports#export_glossaries', as: :export_glossaries

mount Sidekiq::Web, at: "/sidekiq"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/admin_pages_controller.rb
require_relative "admin/config_dicts_controller"
require_relative "admin/config_dict_controller"
require_relative "admin/glossaries_controller"
require_relative "admin/glossaries_import"
require_relative "admin/glossaries_export"

class AdminPagesController < ApplicationController

  before_action :require_login
 
  def admin_home
  end
  def config_user
  end
  def import_dict
	puts("IMPORT DICT")
	puts(params.inspect())
  end

  private

  def require_role(role)
	current_user
	if @current_user==nil
		redirect_to error_path(error: "Bạn chưa đang nhập!")
	else
		if role==""
			return
		end
		if @current_user.role==nil or
		   @current_user.role.index(role)==nil
			redirect_to error_path(error: sprintf("Bạn chưa có quyền : %s ",role))
		end
	end
  end

  def require_login
	require_role("")
  end

end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/_config_dict_form.html.erb
<!--- config-dict-form ----------------------------------------->

<!--- script---------------------------------------------------->
<script>
$(document).ready(function(){
    $("#delete").click(function(){
        console.log("delete");
		$("#want_delete").modal();
		return false;
    });
	$("#submitButton").click(function(){
        $("#want_delete").modal();
		return false;
    });
	$("#yes").click(function(){
        console.log("YES");
		document.getElementById("do_it").value="delete";
		document.getElementById("cfg").submit();
		return false;
    });
	$("#no").click(function(){
        console.log("NO");
		return true;
    });
	console.log("READY!");
});
</script>
<!--- HTML---------------------------------------------------->
<%= hidden_field_tag 'do_it' %>

<!--- FORM---------------------------------------------------->
<div class='container'>
<div class="input-group">
  <input type="text" class="form-control" 
    id="dict_sys_name" name="dict_sys_name"
	placeholder='Nhập tên ngắn thí dụ TD-AV-xx' 
	value="<%=params[:dict_sys_name]%>"
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">Tên hệ thống</span>
</div>
<div class="input-group">
  <input type="text" class="form-control" 
        id="dict_name" name="dict_name"
	placeholder='Nhập tên thí dụ Tự điển Anh Việt ...' 
	value="<%=params[:dict_name]%>" 
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">Tên tự điển</span>
</div>

<div class="input-group">
  <input type="text" class="form-control" 
        id="lang" name="lang"  readonly
	placeholder='' 
	value="<%=params[:lang]%>" 
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">Ngôn ngữ gốc</span>
</div>

<div class="input-group">
  <input type="text" class="form-control" 
        id="xlate_lang" name="xlate_lang" readonly 
	placeholder='' 
	value="<%=params[:xlate_lang]%>"
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">Ngôn ngữ đích</span>
</div>

<div class="input-group">
  <input type="text" class="form-control" 
        id="domains" name="domains"
	placeholder='Nhập [GENERAL,NAT-SCI-TECH,SOC-SCI]..' 
	value="<%=params[:domains]%>" 
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">Lĩnh vực</span>
</div>

<div class="input-group">
 <%= select_tag(
	"protocol", options_for_select(@protocol_options, params[:protocol]), 
	{ "selected" => params[:protocol],
	  "class" =>"form-control" 
	} ) %>
  <span class="input-group-addon" id="basic-addon2">Giao thức</span>
</div>

<div class="input-group">
  <input type="text" class="form-control" 
        id="priority" name="priority" 
	placeholder='số ưu tiên, 0: không dùng, càng cao: ưu tiên dùng tự điển này!' 
	value="<%=params[:priority]%>"
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">Số ưu tiên</span>
</div>

<div class="input-group">
  <textarea class="form-control" rows="4" 
    id="desc" name="desc" ><%=params[:desc]%></textarea>
  <span class="input-group-addon" id="basic-addon2">Mô tả</span>
</div>

<div class="input-group">
  <textarea class="form-control" rows="4" 
    id="cfg" name="cfg" ><%=params[:cfg]%></textarea>
  <span class="input-group-addon" id="basic-addon2">Cấu hình</span>
</div>

<div class="input-group">
<% if params[:dict_sys_name]=="deleted" %>
Đã xóa!
	<a class="btn btn-default btn-sm" href="<%=admin_pages_config_dicts_path%>" role="button">Trở lại</a>
<%else%>

<% if params[:id]==nil or params[:id]=="0" %>
<%= submit_tag "Tạo", {"class"=>"form-control btn btn-secondary btn-sm"} %>
<% else %>
<%= submit_tag "Thay đổi", {"class"=>"form-control btn btn-default btn-sm"} %>
<%= submit_tag "Xóa", {"class"=>"form-control btn btn-default btn-sm","id"=>"delete"} %>


<%end%>

<%end%>
</div>

</div>



<!----- POPUPS --------------------------------------------------------------->
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="want_delete" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Xóa tự điển <%=params[:dict_name]%></h4>
        </div>
        <div class="modal-body">
          <p>Bạn thật sự muốn xóa tự điển này?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  <button type="button" class="btn btn-default" id="yes" data-dismiss="modal">Yes</button>
		  <button type="button" class="btn btn-default" id="no" data-dismiss="modal">No</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/admin_pages/_edit_glossary_form.html.erb
<!--- config-dict-form ----------------------------------------->

<!--- script---------------------------------------------------->
<script>
$(document).ready(function(){
    $("#delete").click(function(){
        console.log("delete");
		$("#want_delete").modal();
		return false;
    });
	$("#submitButton").click(function(){
        $("#want_delete").modal();
		return false;
    });
	$("#yes").click(function(){
        console.log("YES");
		document.getElementById("do_it").value="delete";
		document.getElementById("cfg").submit();
		return false;
    });
	$("#no").click(function(){
        console.log("NO");
		return true;
    });
	console.log("READY!");
});
</script>


<!--- HTML---------------------------------------------------->
<%= hidden_field_tag 'do_it' %>

<!--- FORM---------------------------------------------------->
<div class='container'>

<% @fields.each{|f,v| %>
<div class="input-group">
  <textarea rows="2" cols="60" class="form-control" 
    id="<%=f%>" name="<%=f%>"
	placeholder='' 
	aria-describedby="basic-addon2"><%=@data[f]%></textarea>
  <span class="input-group-addon" id="basic-addon2"><%=v%></span>
</div> <!---input-group --->
<% } %>

<! ACTIONS ----------------------------------------------->
<div class="input-group">

<% if @fields.size==0 %>

   <% if params[:id] != nil and params[:id] != "" and params[:id] != "0" %>
	<p> Đã xóa!</p>
   <% end %>
	<a class="btn btn-default btn-sm"
		href="<%=admin_pages_glossaries_path+'?dict_id='+params[:dict_id]%>" 
		role="button">Trở lại</a> 
<%else%>
  <% if params[:id]==nil or params[:id]=="0" %>
     <%= submit_tag "Tạo", {"class"=>"form-control btn btn-default btn-sm"} %>
  <% else %>
     <%= submit_tag "Thay đổi", {"class"=>"form-control btn btn-default btn-sm"} %>
     <%= submit_tag "Xóa", {"class"=>"form-control btn btn-default btn-sm",
	        "id"=>"delete"} %>
  <%end%>
<%end%>
</div>
<! END-ACTIONS ----------------------------------------------->
</div> <!--- container --->
<!--- END-FORM---------------------------------------------------->


<!----- POPUPS --------------------------------------------------------------->
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="want_delete" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Xóa từ mục<%=params[:dict_name]%></h4>
        </div>
        <div class="modal-body">
          <p>Bạn thật sự muốn xóa từ mục này?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  <button type="button" class="btn btn-default" id="yes" data-dismiss="modal">Yes</button>
		  <button type="button" class="btn btn-default" id="no" data-dismiss="modal">No</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/admin_pages/_glossary_export_form.html.erb
<% src_lang_opt = []
   tgt_lang_opt = []
   ref_lang_opt = []
   @dictionaries.src_lang_supported.each{|k,v|
      src_lang_opt << [v,k]
   }
   @dictionaries.tgt_lang_supported.each{|k,v|
      tgt_lang_opt << [v,k]
   }
%>



<div class="row" >
	<div class="input-group input-group-sm">
		<select class="form-control" id="mode" name="mode" onchange="this.form.submit();" >
			<%= options_for_select(@mode_options,params[:mode]) %>
		</select>
		<span class="input-group-addon" id="basic-addon2">Chọn cách xuất dữ liệu</span>
	</div>
	
	<% if params[:mode] == "export" %>
		<div class="input-group input-group-sm">
			<select class="form-control" id="dict_id" name="dict_id">
				<%= options_for_select(@glossaries_options,params[:dict_id]) %>
			</select>
		<span class="input-group-addon" id="basic-addon2">Chọn tự điển</span>
		</div>
	<% else %>
	
	<div class="input-group input-group-sm">
		<select class="form-control" id="src_lang" 
				name="src_lang" onchange="this.form.submit();">
			<%= options_for_select(src_lang_opt,params[:src_lang]) %>
		</select>
		<span class="input-group-addon" id="basic-addon2">Ngôn ngữ gốc</span>
	</div>
	<div class="input-group input-group-sm">
		<select class="form-control" id="tgt_lang" 
				name="tgt_lang" 		onchange="this.form.submit();">
			<%= options_for_select(tgt_lang_opt,params[:tgt_lang]) %>
		</select>
		<span class="input-group-addon" id="basic-addon2">Ngôn ngữ đích</span>
	</div>

<div class="input-group input-group-sm">
<% @dict_list.each(){|n,inf| %>
	<div class="checkbox">
			<label><input type="checkbox" value="ON"
			name="<%="CHK"+inf["dict_sys_name"]%>"
			id="<%=inf["dict_sys_name"]%>"
			<% if @selected_dicts.has_key?(inf["dict_sys_name"]) %>
				CHECKED
			<% end %>
		><%=inf["dict_name"]%>
		</label>
	</div>

<% } %>
<span class="input-group-addon" id="basic-addon2">Chọn tự điển</span>
</div>
<% end %>
	
<div class="input-group input-group-sm">
  <input type="text" class="form-control" 
        id="notes" name="notes"
	placeholder='Ghi chú (nếu cần thiết)' 
	value="<%=params[:notes]%>"  
	aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">
		<button class="fa fa-pencil" name="submit_a" type="submit_a" value="submit-true">
		</button></span>
</div>
	
	
<div class="input-group input-group-sm">
	<%= submit_tag "Xuất dữ liệu", {"class"=>"form-control btn btn-default btn-sm"} %>
</div>

	
</div> <!---- row  --->


app/views/admin_pages/_glossary_import_form.html.erb

<% @lang_config.each{|f,v| %>
	<%= hidden_field_tag(f,v) %>
<% } %>

<% data_ready= true if @fields != nil and @sample_datas != nil %>

<div class="input-group input-group-sm">
	<select class="form-control" id="dict_id" name="dict_id"  onchange="this.form.submit();">
		<%= options_for_select(@glossaries_options,params[:dict_id]) %>
	</select>
	<span class="input-group-addon" id="basic-addon2">Chọn tự điển</span>
</div>
<div class="input-group input-group-sm">
<span class="input-group-addon" id="basic-addon2">Chọn File</span>
<input type="file" id="imp_file"  name="imp_file" class="form-control form-control-file" >
<span class="input-group-addon" id="basic-addon2">Dữ liệu bắt đầu ở hàng thứ:</span>
<input type="text" class="form-control" id="DATA_START" name="DATA_START"
	placeholder='' 
	value="<%=params[:DATA_START]%>" 
	aria-describedby="basic-addon2">
</div>




<div class="input-group">
	<%= submit_tag "Đọc file", {"class"=>"form-control btn btn-default btn-sm"} %>
    <%= if data_ready 
	       submit_tag "Nhập file", {"class"=>"form-control btn btn-default btn-sm"}
		end
	%>
	<%= if data_ready
		   submit_tag "Bỏ qua", {"class"=>"form-control btn btn-default btn-sm"} 
		end
	%>
</div>

<% if @fields != nil and @sample_datas != nil %>

<div class="row" >
<div class="table-responsive">
<table class="table table-condensed table-striped">

  <thead  class="thead-light">
    <tr>
	  <% @fields.each{|field,value| %>
	    <th><%=value%></th>
	  <% }%>
    </tr>
  </thead>
  <tbody>

		<% @sample_datas.each do |glossary_data|	%>
		   <tr>
		<% 	  @fields.each{|field,value| 			%>
		<%		data = glossary_data[field]			%>
		<%		data = "NA" if data==nil 			%>
				<td><%=data%></td>
		<% 	  }										%>
			</tr>
		<% end 										%>

  </tbody>
</table>

</div> <!--- table-responsive -->
</div> <!--- row  -------------->


<%end%>



app/views/admin_pages/_import_history.html.erb

<div class="row" >
<div class="table-responsive">
<table class="table table-condensed table-striped">
  <tbody>
    <% @import_history.each do |h| %>
      <tr>
	  <% status = ""
	     status << h.status if h.status!= nil
		 if h.percent != nil
			status << " (" 
			status << h.percent.to_s
			status << "%)"
		 end
	   %>
		<td><%=h.in_data%>&nbsp;<i><%=status%></i>&nbsp;[<%=h.message%>]<td>
	  </tr>
    <% end %>
  </tbody>
</table>

</div> <!--- table-responsive -->
</div> <!--- row  -------------->


 






  

app/views/admin_pages/_job_progress.html.erb


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
function update_progress_bar( progress){
	console.log("UPDATE");
	var progress_bar = document.getElementById("progress_bar");
	var progress_msg = document.getElementById("progress_msg");
	var percent=progress.percent;
	if (percent<1){
		percent=1;
	}
	console.log(progress_bar.getAttribute("aria-valuenow"));
	progress_bar.setAttribute("aria-valuenow",percent);
	console.log(progress_bar.getAttribute("aria-valuenow"));
	progress_bar.setAttribute("style","width:"+percent+"%");
	progress_msg.innerHTML= progress.stage + " " + progress.message;
	progress_bar.innerHTML = progress.percent+"%";
	document.getElementById("job_status").value=progress.status;
	if(progress.status=="done" || progress.status=="error" ){
		if (progress.status=="done") {
			progress_msg.innerHTML="Hoàn tất";
			progress_bar.innerHTML = "100%";
			progress_bar.setAttribute("style","width:100%");
			document.getElementById("job_result").value="done";
		} else {
			progress_msg.innerHTML="Lỗi!"
			document.getElementById("job_result").value="error";
		}
		document.getElementById("this_form").submit();
    }
}
function get_progress(){
	var job_id,job_status;
	job_id = document.getElementById("job_id").value;
	job_status = document.getElementById("job_status").value;
	if(job_id!="0" & job_status!="done" & job_status!="error" ){
		$.ajax({
			url: "/progress?id="+job_id,
			dataType: "json",
			success: function(result){
				console.log(result);
				update_progress_bar(result);
				console.log(result.id);
		}});
	}
}
$(document).ready(function(){
	setInterval(get_progress, 1000);
});
</script>


		<div id="progress_msg">JOB</div>
		<div class="progress">
			<div id="progress_bar" class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:0%">
			<span class="sr-only"></span>
			</div>
		</div>


app/views/admin_pages/_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
	<% head.each { |h| %>
	 <p><%=h%></p>
	<% } %>
  </div>
<div class="panel-body">

app/views/admin_pages/_panel_end.html.erb
  </div> <!--- panel body --->
</div> <!--- panel --->

app/views/admin_pages/admin_home.html.erb
<h1>AdminPages#admin_home</h1>
<p>Find me in app/views/admin_pages/admin_home.html.erb</p>

app/views/admin_pages/config_dict.html.erb

<div class="panel panel-default">
  <div class="panel-heading">
    <% if params[:id]==nil or params[:id]=="0"
	      tittle = "Tạo tự điển mới"
	   else
	      name = ""
		  if params[:dict_name] != nil and params[:dict_name] != ""
		     name = params[:dict_name]
		  else 
			if params[:dict_sys_name] != nil and params[:dict_sys_name] != ""
				name = params[:dict_sys_name]
		    else
				name = params[:id]
			end
		  end
		  tittle = "Cấu hình tự điển: "+ name 
	   end
	%>
	<p class="dict_label"><%=tittle%></p>
  </div>

  <div class="panel-body">
    <%= form_with url: admin_pages_config_dict_path , method: :get, local: true ,id: "cfg" do |f| %>
		<%=hidden_field_tag 'id',params[:id] %>
		<%= render "config_dict_form" %>
	<% end %>
  </div>

app/views/admin_pages/glossaries.html.erb
<script>
function hello(){
	console.log("HELLO");
	$("#want_delete").modal();
}
$(document).ready(function(){
	$("#yes").click(function(){
        console.log("YES");
		document.getElementById("do_it").value="delete";
		document.getElementById("cfg").submit();
		return false;
    });
	$("#no").click(function(){
        console.log("NO");
		return true;
    });
	console.log("READY!");
});

</script>

<% options = [] 
   @all_glossaries_configs.each {|inf|
		options << [ inf.dict_name , inf.dict_sys_name ]
   } 
%>

<%= form_with url: admin_pages_glossaries_path ,  method: :get, local: true , id: "cfg" do |f| %>

<%= hidden_field_tag 'do_it' %>   

<div class="container">


<div class="row input-group">

    <select class="form-control" id="dict_id" name="dict_id" onchange="this.form.submit();" >
			<%= options_for_select(options,params[:dict_id]) %>
    </select>
    <span class="input-group-addon">-</span>
	<div class="dropdown">
		<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fa  fa-reorder"></i>
		</button>
		<div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
			<a class="dropdown-item" 
			   href="<%=admin_pages_glossary_edit_path+'?dict_id='+params[:dict_id] %>" 
			   >Thêm từ mục</a>
			<a class="dropdown-item" 
			   href="<%=admin_pages_glossary_import_path+'?dict_id='+params[:dict_id] %>" 
			   >Nhập liệu từ file</a>
			<a class="dropdown-item" 
			   href="<%=admin_pages_glossary_export_path+'?dict_id='+params[:dict_id] %>" 
			   >Kết xuất tự điển ra file</a>
			<a class="dropdown-item" 
			   href="#"
			   onclick="hello();" 
			   >Xóa dữ liệu</a>
		</div>
	</div>

</div>

<div class="row" >
  <div class="input-group">
    <span class="input-group-addon btn btn-default btn-sm " role="button"> 
	    <button class="fa fa-search"></button>
	</span>
    <input id="to_search" type="text" class="form-control" name="to_search"
	value= "<%=params[:to_search] %>" 
	placeholder="Nhập từ muốn kiếm">

  </div>
</div>


	<%= render "notices" %>
 
<%if @fields != nil %>

<div class="row" >
<div class="table-responsive">
<table class="table table-condensed table-striped">

  <thead  class="thead-light">
    <tr>
	  <th></th>
	  <% @fields.each{|field,value| %>
	    <th><%=value%></th>
	  <% }%>
    </tr>
  </thead>
  <tbody>
    <% @glossaries.each do |id,glossary| %>
      <tr>
	  	<td>
			<a class="btn btn-default btn-sm" 
				href="<%=admin_pages_glossary_edit_path + '?' + 'id=' + id.to_s %>"	
				role="button"><i class="fa fa-edit"></i>
			</a>
		</td>
	<% @fields.each{|field,pos|
		data = glossary[field]
		data = "NA" if data==nil
	%>
	    <td><%=data%></td>
	<% }%>
      </tr>
    <% end %>
  </tbody>
</table>

</div> <!--- table-responsive -->
</div> <!--- row  -------------->
</div> <!--- container -->

<% else %>
  <p>Tư điển chưa được cấu hình hay cấu hình sai! </p> 
<% end %>

<% end %>


<!----- POPUPS --------------------------------------------------------------->
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="want_delete" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title">Xóa dữ liệu<%=params[:dict_name]%></h3>
        </div>
        <div class="modal-body">
          <p>Bạn thật sự muốn xóa dữ liệu của tự điển này?</p>
        </div>
        <div class="modal-footer">
		  <button type="button" class="btn btn-default" id="yes" data-dismiss="modal">Yes</button>
		  <button type="button" class="btn btn-default" id="no" data-dismiss="modal">No</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/admin_pages/glossary_export.html.erb
<%= render "notices" %>
<%= form_with url: admin_pages_glossary_export_path, 
				method: :get, id: "this_form" , local: true, multipart: true do |f| %>

  <%= hidden_field_tag('dict_id', params[:dict_id] ) %>
  <%= hidden_field_tag("job_id",params[:job_id]) %>
  <%= hidden_field_tag("job_status",params[:job_status]) %>
  <%= hidden_field_tag("job_result",params[:job_result]) %>

  
	<div class="row">
		<div class="col-sm-6">
			<%=render 'panel' , :head=> ["Xuất dữ liệu tự điển"] %>
			<%=render 'glossary_export_form' %>
			<%=render 'job_progress'		 %>
			<%=render 'panel_end' %>
		</div>
		<div class="col-sm-6">
			<%=render 'panel' , :head=> ["Các dữ liệu đã/đang xuất"] %>
			<%=render 'glossary_exported' %>
			<%=render 'panel_end' %>
		</div>
	</div> <!-- row --->


<%end%> <!--- form --->

app/views/admin_pages/glossary_import.html.erb
<%= render "notices" %>
<%= form_with url: admin_pages_glossary_import_path, 
				method: :put, local: true, id: "this_form",  multipart: true do |f| %>

  <%= hidden_field_tag('dict_id', params[:dict_id] ) %>
  <%= hidden_field_tag('tmp_file_name', params[:tmp_file_name] ) %>
  <%= hidden_field_tag("job_id",params[:job_id]) %>
  <%= hidden_field_tag("job_status",params[:job_status]) %>
  <%= hidden_field_tag("format",params[:format])		 %>
  <%= hidden_field_tag("job_result",params[:job_result]) %>
	<div class="row">
		<div class="col-sm-8">
			<%=render 'panel' , :head=> ["Nhập Data cho tự điển",@dict_config.dict_name] %>
			<%=render 'glossary_import_form' %>
			<%=render 'job_progress'		 %>
			<%=render 'panel_end' %>
		</div>
		<div class="col-sm-4">
			<%=render 'panel' , :head=> ["Đã nhập hôm nay"] %>
			<%=render 'import_history'		 %>
			<%=render 'panel_end' %>
		</div>
	</div> <!-- row --->

<%end%> <!--- form --->

app/views/admin_pages/import_dict.html.erb
<% @admin_job = "davdict" %>
<%= render 'layouts/admin_header' %>

<%= puts("HELLO"+@params.inspect()) %>

<%= form_with url: '/dict_import', method: :put, dict_id: params[:dict_id] , local: true, multipart: true do |f| %>
  <%= f.text_field :to_search, id: :to_search , value:  params[:to_search] %>
  <%= f.file_field :import_file %>
  <%= f.submit "Search" %>
<% end %>