config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  resources :data_files
  resources :dict_jobs
  resources :glossary_indices
  resources :progress_bars
  resources :users
  get 'export_glossary/export'
  get 'export_glossary/export_now'

  resources :glossaries
  resources :davkhkt_dicts
  resources :dict_configs
  root 'dict_pages#home'
  get 'admin_pages/admin_home'
  get 'admin_pages/config_dict'
  get 'admin_pages/config_dict_new'
  get 'admin_pages/config_dicts'
  get 'admin_pages/glossaries'
  get 'admin_pages/glossary_edit'
  get 'admin_pages/glossary_import'
  put 'admin_pages/glossary_import'
  get 'admin_pages/glossary_export'
  put 'admin_pages/glossary_export'
  get 'admin_pages/config_user'
  get '/home',    to: 'dict_pages#home'
  get '/help',    to: 'dict_pages#help'
  get '/about',   to: 'dict_pages#about'
  get '/error',   to: 'dict_pages#error'
  get '/admin',   to: 'dict_pages#admin'
  get '/signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  get '/dict_lookup',   to: 'dict_pages#dict_lookup'
  get '/dict_add',   to: 'dict_pages#dict_add'
  put '/glossaries',   to: 'glossaries#index'
  get '/progress' => 'dict_jobs#progress'

#  put  '/davkhkt_dicts',   to: 'davkhkt_dicts#index'
#  get 'dav_dict_pages/import'
#  get 'dav_dict_pages/show'
#  put  '/dict_import',   to: 'import_page#import_glossary'
#  get  '/dict_import',   to: 'import_page#import_glossary'
#  put  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get 'export_glossaries' => 'exports#export_glossaries', as: :export_glossaries

mount Sidekiq::Web, at: "/sidekiq"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/dict_config.rb
class DictConfig < ApplicationRecord
   def find_by_sys_name(dict_sys_name=nil)
      dict_sys_name=self.dict_sys_name if dict_sys_name==nil
      return rec = DictConfig.find_by(dict_sys_name: dict_sys_name)
   end
end

app/controllers/dict_configs_controller.rb
class DictConfigsController < ApplicationController
  before_action :set_dict_config, only: [:show, :edit, :update, :destroy]

  # GET /dict_configs
  # GET /dict_configs.json
  def index
	printf("CFG %s\n",params.inspect())
    if params[:dict_name] != nil and  params[:dict_name] != ""
	printf("---\n")
       @dict_configs = DictConfig.where("dict_name like ?","%"+params[:dict_name]+"%").order(priority: :desc, dict_name: :asc) 
    else
       @dict_configs = DictConfig.order(priority: :desc, dict_name: :asc) 
    end
  end

  # GET /dict_configs/1
  # GET /dict_configs/1.json
  def show
  end

  # GET /dict_configs/new
  def new
    @dict_config = DictConfig.new
  end

  # GET /dict_configs/1/edit
  def edit
  end

  # POST /dict_configs
  # POST /dict_configs.json
  def create
    cfg_params= dict_config_params
    cfg_params[:dict_sys_name]=cfg_params[:dict_sys_name].strip()
    @dict_config = DictConfig.new(cfg_params)

    respond_to do |format|
      ok = 1
      if @dict_config.find_by_sys_name() != nil
        @dict_config.errors.add(:dict_sys_name, :invalid, message: "dict_sys_name already used!")
        ok = 0
      end
      if ok == 1 and @dict_config.save
        format.html { redirect_to @dict_config, notice: 'Dict config was successfully created.' }
        format.json { render :show, status: :created, location: @dict_config }
      else
        format.html { render :new }
        format.json { render json: @dict_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dict_configs/1
  # PATCH/PUT /dict_configs/1.json
  def update
    respond_to do |format|
      ok = 1
      cfg_params= dict_config_params
      cfg_params[:dict_sys_name]=cfg_params[:dict_sys_name].strip()
      rec=@dict_config.find_by_sys_name(cfg_params[:dict_sys_name])
      if rec != nil and rec.id != @dict_config.id 
        @dict_config.errors.add(:dict_sys_name, :invalid, message: "dict_sys_name already used!")
        ok = 0
      end
      if ok==1 and @dict_config.update(cfg_params)
        format.html { redirect_to @dict_config, notice: 'Dict config was successfully updated.' }
        format.json { render :show, status: :ok, location: @dict_config }
      else
        format.html { render :edit }
        format.json { render json: @dict_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dict_configs/1
  # DELETE /dict_configs/1.json
  def destroy
    @dict_config.destroy
    respond_to do |format|
      format.html { redirect_to dict_configs_url, notice: 'Dict config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dict_config
      @dict_config = DictConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dict_config_params
      params.require(:dict_config).permit(:dict_sys_name, :dict_name, :lang, :xlate_lang, :desc, :protocol, :url, :syntax, :ext_infos,:cfg,:priority,:dict_id)
    end
end

app/helpers/dict_configs_helper.rb
module DictConfigsHelper
end

app/views/dict_configs/_form.html.erb
<%= form_with(model: dict_config, local: true  ) do |form| %>
  <% if dict_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dict_config.errors.count, "error") %> prohibited this dict_config from being saved:</h2>

      <ul>
      <% dict_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
<div class="container-fluid form-horizontal">
<div class="row">
  <div class="form-group">
	<%= form.label "dict_id" , {"class"=> "col-sm-4"} %>
    <%= form.text_field :dict_sys_name, id: :dict_config_dict_sys_name, class: "col-sm-10" %>
  </div>
  <div class="form-group">
    <%= form.label "Tên tự điển" , {"class"=> "col-sm-4"}%>
    <%= form.text_field :dict_name, id: :dict_config_name, class: "col-sm-10"%> 
  </div>
</div>
    <%= form.label "Ngôn ngữ gốc" , {"class"=> "col-sm-2"}%>
    <%= form.text_field :lang, id: :dict_config_lang , class: "col-sm-2"%>
<br/>
    <%= form.label "Ngôn ngữ đích" , {"class"=> "col-sm-2"}%>
    <%= form.text_field :xlate_lang, id: :dict_config_xlate_lang, size: "100" %>
<br/>
    <%= form.label "Mô tả" , {"class"=> "col-sm-2"}%>
    <%= form.text_area :desc, id: :desc%>
<br/>
    <%= form.label "Priority" , {"class"=> "col-sm-2"}%>
    <%= form.text_field :priority, id: :priority %>
<br/>
    <%= form.label "Protocol" , {"class"=> "col-sm-2"}%>
    <%= form.text_field :protocol, id: :dict_config_protocol%>
<br/>
    <%= form.label "Url" , {"class"=> "col-sm-2"}%>
    <%= form.text_field :url, id: :dict_config_url %>
<br/>
    <%= form.label "CFG" , {"class"=> "col-sm-2"} %>
    <%= form.text_area :cfg, id: :dict_config_cfg %>

</div> 

<div class="actions">
    <%= form.submit %>
</div>


<% end %>

app/views/dict_configs/edit.html.erb
<%= render 'form', dict_config: @dict_config %>

app/views/dict_configs/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_with url: dict_configs_path, method: :get, local: true, multipart: true do |f| %>
<table class="table table-condensed table-striped">
  <thead>
    <tr class="active">
      <th>Mã hệ thống</th>
      <th>Tên tự điển</th>
      <th>Ngôn ngữ gốc</th>
      <th>Ngôn ngữ đích</th>
      <th>Protocol</th>
      <th>Priority</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>
		<a class="btn btn-default btn-sm" href="<%=new_dict_config_path%>" role="button">Thêm tự điển</a>
      </th>
      <th>
		<div class="input-group input-group-sm">
			<input type="text" id="dict_name" name="dict_name" class="form-control" 
				value="<%=params[:dict_id]%>" placeholder="Nhập một phần tên để tìm">
		</div><!-- /input-group -->
	  </th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  
  
    <% @dict_configs.each do |dict_config| %>
      <tr>
        <td><%= dict_config.dict_sys_name %></td>
        <td><%= dict_config.dict_name %></td>
        <td><%= dict_config.lang %></td>
        <td><%= dict_config.xlate_lang %></td>
        <td><%= dict_config.protocol %></td>
        <td><%= dict_config.priority %></td>
<div class="btn-group">
        <td><%= link_to 'Chi tiết', dict_config %></td>
        <td><%= link_to 'Thay đổi', edit_dict_config_path(dict_config) %></td>
        <td><%= link_to 'Hủy', dict_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% if dict_config.protocol=='glossary' %>
        	<td><%= link_to 'Nhập liệu',dict_import_path(:dict_id=>dict_config.dict_sys_name) %></td>
	<% end %>
</div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%end%>

app/views/dict_configs/new.html.erb
<%= render 'form', dict_config: @dict_config %>

app/views/dict_configs/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover table-bordered table-sm">

  <tr>
    <td bgcolor=tabhead_color><strong>Dict_ID:</strong> </td>
    <td><%= @dict_config.dict_sys_name %> </td>
  </tr>
  <tr>
    <td bgcolor=tabhead_color><strong>Tên tự điển:</strong> </td>
    <td><%= @dict_config.dict_name %> </td>
  </tr>

  <tr>
    <td bgcolor=tabhead_color><strong>Ngôn ngữ gốc:</strong> </td>
    <td><%= @dict_config.lang %> </td>
  </tr>

  <tr>
    <td bgcolor=tabhead_color><strong>Ngôn ngữ đích:</strong> </td>
    <td><%= @dict_config.xlate_lang %> </td>
  </tr>

  <tr>
    <td bgcolor=tabhead_color><strong>Mô tả:</strong> </td>
    <td><%= @dict_config.desc %> </td>
  </tr>
  <tr>
    <td bgcolor=tabhead_color><strong>Priority:</strong> </td>
    <td><%= @dict_config.priority %> </td>
  </tr>
  <tr>
    <td bgcolor=tabhead_color><strong>Protocol:</strong> </td>
    <td><%= @dict_config.protocol %> </td>
  </tr>

  <tr>
    <td bgcolor=tabhead_color><strong>Url:</strong> </td>
    <td><%= @dict_config.url %> </td>
  </tr>

  <tr>
    <td bgcolor=tabhead_color><strong>Syntax:</strong> </td>
    <td><%= @dict_config.syntax %> </td>
  </tr>

  <tr>
    <td bgcolor=tabhead_color><strong>Ext infos:</strong> </td>
    <td><%= @dict_config.ext_infos %> </td>
  </tr>
  <tr>
    <td bgcolor=tabhead_color><strong>CFG :</strong> </td>
    <td><%= @dict_config.cfg %> </td>
  </tr>
</table>

<%= link_to 'Edit', edit_dict_config_path(@dict_config) %> |