config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  resources :data_files
  resources :dict_jobs
  resources :glossary_indices
  resources :progress_bars
  resources :users
  get 'export_glossary/export'
  get 'export_glossary/export_now'

  resources :glossaries
  resources :davkhkt_dicts
  resources :dict_configs
  root 'dict_pages#home'
  get 'admin_pages/admin_home'
  get 'admin_pages/config_dict'
  get 'admin_pages/config_dict_new'
  get 'admin_pages/config_dicts'
  get 'admin_pages/glossaries'
  get 'admin_pages/glossary_edit'
  get 'admin_pages/glossary_import'
  put 'admin_pages/glossary_import'
  get 'admin_pages/glossary_export'
  put 'admin_pages/glossary_export'
  get 'admin_pages/config_user'
  get '/home',    to: 'dict_pages#home'
  get '/help',    to: 'dict_pages#help'
  get '/about',   to: 'dict_pages#about'
  get '/error',   to: 'dict_pages#error'
  get '/admin',   to: 'dict_pages#admin'
  get '/signup',   to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  get '/dict_lookup',   to: 'dict_pages#dict_lookup'
  get '/dict_add',   to: 'dict_pages#dict_add'
  put '/glossaries',   to: 'glossaries#index'
  get '/progress' => 'dict_jobs#progress'

#  put  '/davkhkt_dicts',   to: 'davkhkt_dicts#index'
#  get 'dav_dict_pages/import'
#  get 'dav_dict_pages/show'
#  put  '/dict_import',   to: 'import_page#import_glossary'
#  get  '/dict_import',   to: 'import_page#import_glossary'
#  put  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get  '/dict_import_commit',   to: 'import_page#import_glossary_commit'
#  get 'export_glossaries' => 'exports#export_glossaries', as: :export_glossaries

mount Sidekiq::Web, at: "/sidekiq"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/layouts/_admin_header.erb
<admin_header class="navbar">

<% 
	tabs= [
		{"admin_job" =>"cfgdict",
		 "text"=>"Cấu hình các tự điển",
		 "path"=>dict_configs_path },
		{"admin_job" =>"glossary",
		 "text"=>"Bảng thuật ngữ",
		 "path"=>glossaries_path },
		{"admin_job" =>"export_glossary",
		 "text"=>"Kết xuất thuật ngữ",
		 "path"=>"export_glossary/export" }
	]
	
%>
 <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ADMIN</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav">
		<% cl="" %>
		<% tabs.each {|tb| %>
			<%  if @admin_job==tb["admin_job"]
					cl = "active"
				else
					cl = "inactive"
				end
			%>
			<li class="<%=cl%>" ><%= link_to tb["text"], tb["path"] %>
		<%}					%>
      </ul>


<% if defined?(@navlinks) != nil %>
     <ul class="nav navbar-nav navbar-right">
<% 	@navlinks.each{|l|   %>
	<li><%= link_to l[0],l[1] %></li>
<% 	}   %>
      </ul>
<% end %>

     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>


</admin_header>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light ">
  <a class="navbar-brand" href="#">TỪ ĐIỂN TỔNG HỢP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav justify-content-end">
		<li><a class="nav-link" href=<%=dict_lookup_path%>>Tra từ</a></li>
		<li><a class="nav-link" href=<%=dict_add_path%>>Bổ sung từ mục</a></li>
	
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 	data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Tài khoản
			</a>
			<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
				<a class="dropdown-item" href=<%=login_path%>>Đăng nhập</a>
				<a class="dropdown-item" href=<%=logout_path%>>Đăng xuất</a>
				<a class="dropdown-item" href=<%=signup_path%>>Đăng ký</a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item" href="#"><%=current_user_name%></a>
				
			</div>
		</li>		
		<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 	data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Quản lý
			</a>
			<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
				<a class="dropdown-item" href=<%=admin_pages_config_dicts_path%>>Cấu hình tự điển</a>
				<a class="dropdown-item" href=<%=admin_pages_glossaries_path%>>Bảng thuật ngữ</a>
				<a class="dropdown-item" href=<%=admin_pages_glossary_import_path%>>Nhập bảng thuật ngữ</a>
				<a class="dropdown-item" href=<%=admin_pages_glossary_export_path%>>Xuất bảng thuật ngữ</a>
			</div>
		</li>
	</ul>
  </div>
  
  
</nav>

app/views/layouts/_notices.html.erb
<!--- SHOW NOTICE ---> 
<% if @notice!=nil %>
<div class="alert alert-success">
   <% @notice.split("\n").each{|l| %>
		<p><%=l%>
   <%}%>
</div>
<%end%>

<!--- SHOW WARNING --->

<% if @warning!=nil %>
<div class="alert alert-danger">
   <% @warning.split("\n").each{|l| %>
		<p><%=l%>
   <%}%>
</div>
<%end%>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
 			'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_sub_header.html.erb
<div id="exTab2" class="container">	
<ul class="nav nav-tabs">
	<li class="active">
        	<a  href="#1" data-toggle="tab">Overview</a>
	</li>
	<li><a href="#2" data-toggle="tab">Without clearfix</a>
	</li>
	<li><a href="#3" data-toggle="tab">Solution</a>
	</li>
</ul>

  <div class="tab-content ">
	<div class="tab-pane active" id="1">
       		<h3>Standard tab panel created on bootstrap using nav-tabs</h3>
	</div>
	<div class="tab-pane" id="2">
          <h3>Notice the gap between the content and tab after applying a background color</h3>
	</div>
        <div class="tab-pane" id="3">
          <h3>add clearfix to tab-content (see the css)</h3>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
	
	
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	
	
	
	
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notices' %>

<div class="container-fluid">
      <%= yield %>
</div>
<div class="container-fluid">
      <%= render 'layouts/footer' %>
</div>
  </body>
</html>